---
title: "Methylation_R_scripts"
output: html_document
date: "2025-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Libraries
```{r}
library(ggplot2)
library(dplyr)
library(data.table)
```

# Colors
```{r}
cols <- c(
  "#FF0000", "#00FF00", "#0000FF", "#FFFF00", "#FF00FF", "#00FFFF", "#800000", "#008000",
  "#000080", "#808000", "#800080", "#008080", "#FF4500", "#2E8B57", "#4682B4", "#DAA520",
  "#FF1493", "#9ACD32", "#8A2BE2", "#5F9EA0", "#D2691E", "#DC143C", "#B8860B", "#32CD32",
  "#FFD700", "#20B2AA", "#FF6347", "#4169E1", "#8B4513", "#6A5ACD", "#FF7F50", "#2F4F4F")
```

# Feature Importance
```{r}
feature_importance <- read.delim("~/Desktop/Git/Methylation/R/Methylation_R/RFiles/feature_importance.txt")
df <- feature_importance[rownames(feature_importance) != "All", ]
df$Features <- as.numeric(df$Features)

value_h <- feature_importance[grep("All", feature_importance$Features), ]
value_h = print(value_h["Accuracy.Test"][ ,])

value_v <- 150

p <- ggplot(df, aes(x=Features, y=Accuracy.Test)) + ggtitle("Feature Importance") +
  geom_line() + theme_bw() +
  theme(text = element_text(family = "Palatino"),
    plot.title = element_text(size = 34),
    axis.title = element_text(size = 34),
    axis.text = element_text(size = 28))
p1 <- p + geom_hline(yintercept=value_h, linetype="dashed", color = "red", linewidth = 2) +
  geom_text(aes(230, value_h, label = "All features", vjust = - 1),
            color = "red", family = "Palatino", size = 10)
p2 <- p1 + geom_vline(xintercept=value_v, linetype="dotdash", color = "blue", linewidth = 1)
p2

ggsave(filename = "plots/feature_importance.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)
```
# Analysis of Kaiju results
```{r}
kaiju_summary <- read.delim("~/Desktop/Git/Methylation/R/Methylation_R/RFiles/kaiju_summary.tsv")

# Remove extra column headers
kaiju_summary <- kaiju_summary[- grep("sample", kaiju_summary$sample),]

# Into numeric
kaiju_summary$percent <- as.numeric(kaiju_summary$percent)

# Top % 1?
kaiju_summary_filt <- kaiju_summary %>% filter(percent > 1)

# Do some editing for plotting
kaiju_summary_filt$sample <- gsub("bcAd1023T--bcAd1023T", "bcAd1023T", kaiju_summary_filt$sample)
kaiju_summary_filt$sample <- gsub("bcAd1037T--bcAd1037T", "bcAd1037T", kaiju_summary_filt$sample)
kaiju_summary_filt$sample <- gsub("bcAd1039T--bcAd1039T", "bcAd1039T", kaiju_summary_filt$sample)
kaiju_summary_filt$sample <- gsub("bcAd1046T--bcAd1046T", "bcAd1046T", kaiju_summary_filt$sample)
kaiju_summary_filt$sample <- gsub("bcAd1063T--bcAd1063T", "bcAd1063T", kaiju_summary_filt$sample)

# Add sample info
kaiju_summary_filt$sample_info <- ifelse(kaiju_summary_filt$sample == "bcAd1023T", "High", "Low")

kaiju_summary_filt <- kaiju_summary_filt %>%
  mutate(sample_info = case_when(
    sample == "bcAd1023T" ~ "Tetracycline: 0.2, 15 ªC, rep-5 (bcAd1023T)",
    sample == "bcAd1037T" ~ "Sulfonamide: 20, 25 ªC, rep-3 (bcAd1037T)",
    sample == "bcAd1039T" ~ "Sulfonamide: 20, 25 ªC, rep-4 (bcAd1039T)",
    sample == "bcAd1046T" ~ "Tetracycline: 0.02, 37 ªC, rep-3 (bcAd1046T)",
    sample == "bcAd1063T" ~ "no ab, 7 ªC, rep-3 (bcAd1063T)",
  ))
kaiju_summary_filt$sample_info = factor(kaiju_summary_filt$sample_info, 
                                        levels=c("Tetracycline: 0.2, 15 ªC, rep-5 (bcAd1023T)",
                                                  "Sulfonamide: 20, 25 ªC, rep-3 (bcAd1037T)",
                                                  "Sulfonamide: 20, 25 ªC, rep-4 (bcAd1039T)",
                                                  "Tetracycline: 0.02, 37 ªC, rep-3 (bcAd1046T)",
                                                  "no ab, 7 ªC, rep-3 (bcAd1063T)"))
```
## Plot
```{r}
cols <- c("#34495E","#3498DB", "#87F28A", "#F1C40F", "#9B59B6", "#1ABC9C","#E74C3C", 
          "black", "#FFB6B0", "#8C510A", "#808000", "#00FFFF", "#FF00FF", "grey")

kaiju_summary_filt$taxon_name <- factor(kaiju_summary_filt$taxon_name, 
                                        levels=c('Acinetobacter', 'Aeromonas', 'Agrobacterium',
                                                 'Azorhizobium', 'Azospirillum', 'Citrobacter',
                                                 'Elizabethkingia', 'Enterococcus', 'Kluyvera',
                                                 'Paracoccus', 'Pseudomonas', 'Sphingobacterium',
                                                 'Sphingobium', 'cannot be assigned to a (non-viral) genus'))
  
p <- ggplot(kaiju_summary_filt, aes(x = sample, y = percent, fill = taxon_name)) + 
  geom_bar(stat = "identity") + theme_minimal() + 
  ggtitle("Bacterial composition, HAMBI dataset (Kaiju)") +
  scale_y_continuous(expand = c(0,0), limits = c(0,100)) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(face = "italic", size = 30),
        legend.title = element_blank(),
        axis.title = element_blank(),
        strip.text = element_text(size = 18),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_blank(),
        plot.title = element_text(size = 30)) + 
  scale_fill_manual(values=c(cols)) + 
  facet_grid(~sample_info, space = "free", scale = "free", 
             labeller = label_wrap_gen(width=16), switch = "both")
p

ggsave(filename = "plots/kaiju.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)
```

# HiFi MAG Pipeline results
```{r}
# Load data
hifi_MAG_pipeline_results <- read.delim("~/Desktop/Git/Methylation/R/Methylation_R/RFiles/hifi_MAG_pipeline_results.txt", row.names=1)

# List High-quality MAGs
HQ_MAGs <- hifi_MAG_pipeline_results %>%
  filter(Completeness >= 90 & Contamination <= 5)

# Filter those that have ARGs
HQ_MAGs_with_ARGs <- HQ_MAGs %>%
  filter(ARG != "NA")

# Count HQ MAGs/sample
HQ_MAG_count_sample <- HQ_MAGs %>% count(Sample)

# Count HQ MAGs/taxa
HQ_MAG_count_species <- HQ_MAGs %>% count(species)
HQ_MAG_count_genus <- HQ_MAGs %>% count(genus)
HQ_MAG_count_class <- HQ_MAGs %>% count(class)
HQ_MAG_count_phylum <- HQ_MAGs %>% count(phylum)

# Count HQ MAGs/taxa/Sample
HQ_MAG_count_species_sample <- HQ_MAGs %>% count(species, Sample)
HQ_MAG_count_genus_sample <- HQ_MAGs %>% count(genus, Sample)
HQ_MAG_count_class_sample <- HQ_MAGs %>% count(class, Sample)
HQ_MAG_count_phylum_sample <- HQ_MAGs %>% count(phylum, Sample)

# Get statistics
hifi_MAG_pipeline_stats <- hifi_MAG_pipeline_results %>%
  summarize(mean_contigs = mean(Contig_Number),
            mean_completeness = mean(Completeness),
            mean_contamination = mean(Contamination),
            max_completeness = max(Completeness),
            min_completeness = min(Completeness),
            max_contamination = max(Contamination),
            min_contamination = min(Contamination))

# Filter those that have ARGs (all MAGs)
MAGs_with_ARGs <- hifi_MAG_pipeline_results %>%
  filter(ARG != "NA")

# MAGs with any ARGs
MAGs_with_ARGs <- hifi_MAG_pipeline_results %>%
  filter(ARG != "NA")

# erm(F) hosts
MAGs_with_erm <- hifi_MAG_pipeline_results %>%
  filter(grepl("erm", ARG))

# Count MAGs/sample
MAG_count_sample <- hifi_MAG_pipeline_results %>% count(Sample)

# Count MAGs/taxa
MAG_count_species <- hifi_MAG_pipeline_results %>% count(species)
MAG_count_genus <- hifi_MAG_pipeline_results %>% count(genus)
MAG_count_class <- hifi_MAG_pipeline_results %>% count(class)
MAG_count_phylum <- hifi_MAG_pipeline_results %>% count(phylum)

# Count MAGs/taxa/Sample
MAG_count_species_sample <- hifi_MAG_pipeline_results %>% count(species, Sample)
MAG_count_genus_sample <- hifi_MAG_pipeline_results %>% count(genus, Sample)
MAG_count_class_sample <- hifi_MAG_pipeline_results %>% count(class, Sample)
MAG_count_phylum_sample <- hifi_MAG_pipeline_results %>% count(phylum, Sample)
```
# Plot HiFi MAG Pipeline results
## HQ
```{r}
# colors
cols <- c("EFF1" = "#17b2c2", "EFF2" = "#47ecfd", "EFF3" = "#29b3fc",
            "INF1" = "#f9e30a", "INF2" = "#fcf0a0", "INF3" = "#eac51e",
            "SLU1" = "#e38236", "SLU2" = "#fec191", "SLU3" = "#daa187")

# HQ MAGs/taxa/Sample
## Phylum
p <- ggplot(HQ_MAG_count_phylum_sample, aes(x = phylum, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("High-quality MAGs by HiFi MAG Pipeline (phylum)") +
  scale_y_continuous(expand = c(0,0), limits = c(0,45)) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 30),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_text(size = 16, angle = 55, hjust = 0.95),
        plot.title = element_text(size = 30))
p

ggsave(filename = "plots/HQ_MAGs_phylum.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

## Class
p <- ggplot(HQ_MAG_count_class_sample, aes(x = class, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("High-quality MAGs by HiFi MAG Pipeline (class)") +
  scale_y_continuous(expand = c(0,0), limits = c(0,45)) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 30),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_text(size = 16, angle = 55, hjust = 0.95),
        plot.title = element_text(size = 30))
p

ggsave(filename = "plots/HQ_MAGs_class.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

## Genus
p <- ggplot(HQ_MAG_count_genus_sample, aes(x = genus, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("High-quality MAGs by HiFi MAG Pipeline (genus)") +
  scale_y_continuous(expand = c(0,0), limits = c(0,45)) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10, angle = 65, hjust = 0.95, face = "italic"),
        plot.title = element_text(size = 20))
p

ggsave(filename = "plots/HQ_MAGs_genus.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

## Species
p <- ggplot(HQ_MAG_count_species_sample, aes(x = species, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("High-quality MAGs by HiFi MAG Pipeline (species)") +
  scale_y_continuous(expand = c(0,0), limits = c(0,45)) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 10),
        axis.text.x = element_text(size = 10, angle = 65, hjust = 0.95, face = "italic"),
        plot.title = element_text(size = 20))
p

ggsave(filename = "plots/HQ_MAGs_species.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)
```

# Plot HiFi MAG Pipeline results
## All
```{r}
# MAGs/taxa/Sample
## Phylum
p <- ggplot(MAG_count_phylum_sample, aes(x = phylum, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("All MAGs by HiFi MAG Pipeline (phylum)") +
  scale_y_continuous(expand = c(0,0)
                     #, limits = c(0,50)
                     ) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 30),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_text(size = 16, angle = 65, hjust = 0.95),
        plot.title = element_text(size = 30))
p

ggsave(filename = "plots/MAGs_phylum.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

# MAGs/taxa/Sample
## Class
p <- ggplot(MAG_count_class_sample, aes(x = class, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("All MAGs by HiFi MAG Pipeline (class)") +
  scale_y_continuous(expand = c(0,0)
                     #, limits = c(0,50)
                     ) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 30),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_text(size = 16, angle = 60, hjust = 0.99),
        plot.title = element_text(size = 30))
p

ggsave(filename = "plots/MAGs_class.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

# MAGs/taxa/Sample
## Genus
p <- ggplot(MAG_count_genus_sample, aes(x = genus, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("All MAGs by HiFi MAG Pipeline (genus)") +
  scale_y_continuous(expand = c(0,0)
                     #, limits = c(0,45)
                     ) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 20),
        axis.text.x = element_text(size = 8, angle = 90, face = "italic", vjust = 0.5, hjust=1),
        plot.title = element_text(size = 20))
p

ggsave(filename = "plots/MAGs_genus.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

# MAGs/taxa/Sample
## Species
p <- ggplot(MAG_count_species_sample, aes(x = species, y = n, fill = Sample)) + 
  geom_bar(stat = "identity") + scale_fill_manual(values = c(cols)) + theme_minimal() +
  ggtitle("All MAGs by HiFi MAG Pipeline (species)") +
  scale_y_continuous(expand = c(0,0)
                     #, limits = c(0,50)
                     ) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 20),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 20),
        axis.text.x = element_text(size = 8, angle = 90, face = "italic", vjust = 0.5, hjust=1),
        plot.title = element_text(size = 20))
p

ggsave(filename = "plots/MAGs_species.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

# Pie chart
MAG_count_phylum_sample_INF <- MAG_count_phylum_sample[grepl("INF", MAG_count_phylum_sample$Sample), ]
MAG_count_phylum_sample_EFF <- MAG_count_phylum_sample[grepl("EFF", MAG_count_phylum_sample$Sample), ]
MAG_count_phylum_sample_SLU <- MAG_count_phylum_sample[grepl("SLU", MAG_count_phylum_sample$Sample), ]

# Colors
cols <- c("Acidobacteriota"	= "#d1495b","Actinobacteriota" = "#edb183","Armatimonadota"	= "#c0caad","Bacteroidota"	= "#ffb400",
"Caldisericota"	= "#f28500","Campylobacterota"	= "#a593e0","Chloroflexota"	= "#70c1b3","Cloacimonadota"	= "#547aa5",
"Desulfobacterota"	= "#5e4fa2","Desulfobacterota_G"	= "#3b528b","Firmicutes"	= "#abdda4","Firmicutes_A"	= "#66c2a5",
"Firmicutes_B"	= "#3288bd","Firmicutes_G"	= "#1b9e77","Halobacteriota"	= "#e7298a","Hydrogenedentota"	= "#e6ab02",
"JAFGOL01"	= "#a6761d","Methanobacteriota_B"	= "#666666","Micrarchaeota"	= "#f0027f","Myxococcota"	= "#bf5b17",
"Nanoarchaeota"	= "#984ea3","Patescibacteria"	= "#ff7f00","Planctomycetota"	= "#a6cee3","Proteobacteria"	= "#1f78b4",
"Ratteibacteria" =	"#b2df8a","Thermoplasmatota" =	"#cab2d6","Thermotogota"	= "#fb9a99","Verrucomicrobiota" =	"#33a02c")

#p <- ggplot(MAG_count_phylum_sample_INF, aes(x = "", y = n, fill = phylum)) +
#p <- ggplot(MAG_count_phylum_sample_EFF, aes(x = "", y = n, fill = phylum)) +
p <- ggplot(MAG_count_phylum_sample_SLU, aes(x = "", y = n, fill = phylum)) +
  geom_col() + scale_fill_manual(values = c(cols)) +
  #ggtitle("Influent") +
  #ggtitle("Effluent") +
  ggtitle("Sludge") +
  theme_minimal() +
  theme(text = element_text(family = "Palatino"),
        panel.background = element_blank(),
        plot.background = element_blank(),
        panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_text(size = 20),
        plot.title = element_text(size = 30, hjust = 0.5),
        legend.text = element_text(size = 20),
        legend.title = element_blank()) +
  coord_polar(theta = "y")
p

ggsave(filename = "plots/MAGs_pie_INF.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

ggsave(filename = "plots/MAGs_pie_EFF.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)

ggsave(filename = "plots/MAGs_pie_SLU.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)
```

# Plot HiFi MAG Pipeline results
## Summary plot
```{r}
colnames(MAG_count_sample) <- c("Sample", "other_MAGs")
colnames(HQ_MAG_count_sample) <- c("Sample", "HQ_MAGs")

MAG_counts <- cbind(MAG_count_sample, "HQ_MAGs" = HQ_MAG_count_sample$HQ_MAGs)

long_MAG_counts <- melt(setDT(MAG_counts), id.vars = c("Sample"), variable.name = "MAGs")
colnames(long_MAG_counts) <- c("sample", "MAGs", "count")

# Colors
#cols <- c("#87bbda", "#0540a0")

cols <- c("#17b2c2", "#47ecfd", "#29b3fc", "#f9e30a", "#fcf0a0", "#eac51e","#e38236","#fec191", "#daa187")

#cols <- c("EFF1" = "#17b2c2", "EFF2" = "#47ecfd", "EFF3" = "#29b3fc","INF1" = "#f9e30a", "INF2" = "#fcf0a0", "INF3" = "#eac51e","SLU1" = "#e38236", "SLU2" = "#fec191", "SLU3" = "#daa187")

# Reorder
long_MAG_counts$sample <- factor(long_MAG_counts$sample,
                                 levels=c("INF1", "INF2", "INF3",
                                          "EFF1", "EFF2", "EFF3",
                                          "SLU1", "SLU2", "SLU3"))
# Add ARGs
counts_MAGs_with_ARGs <- MAGs_with_ARGs %>% count(Sample)
View(counts_MAGs_with_ARGs)

counts_HQ_MAGs_with_ARGs <- HQ_MAGs_with_ARGs %>% count(Sample)
View(counts_HQ_MAGs_with_ARGs)

ARGs <- data.frame(sample = c("EFF1","EFF2","EFF3", "INF1","INF2","INF3","SLU1","SLU2","SLU3",
                              "EFF1","EFF2","EFF3","INF1","INF2","INF3","SLU1","SLU2","SLU3"),
                   MAGs = c("other_MAGs", "other_MAGs", "other_MAGs", "other_MAGs", "other_MAGs",
                            "other_MAGs", "other_MAGs", "other_MAGs", "other_MAGs",
                            "HQ_MAGs", "HQ_MAGs", "HQ_MAGs", "HQ_MAGs", "HQ_MAGs", "HQ_MAGs", "HQ_MAGs", "HQ_MAGs", "HQ_MAGs"),
                   ARGs = c(0,1,0,0,0,0,3,2,1,
                            0,1,0,0,0,0,0,2,2))

long_MAG_counts$ARGs <- as.numeric(ARGs$ARGs)

long_MAG_counts$ARGs[long_MAG_counts$ARGs == 0] <- ' '

# Plot
p <- ggplot(long_MAG_counts, aes(x = sample, y = count, fill = MAGs, label = ARGs)) + 
  geom_bar(stat = "identity", alpha = 0.5) + scale_fill_manual(values = c(cols)) + theme_minimal() +
  geom_text(size = 10, position = position_stack(vjust = .5), color = "red", family = "Courier",) +
  ggtitle("Number of MAGs by HiFi MAG Pipeline") +  theme_minimal() +
  scale_y_continuous(expand = c(0,0)) +
  theme(
        text = element_text(family = "Palatino"),
        legend.text = element_text(size = 30),
        legend.title = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_text(size = 24, face = "bold"),
        plot.title = element_text(size = 30))
p


p <- ggplot(long_MAG_counts, aes(x = sample, y = count, fill = interaction(sample, MAGs), label = ARGs)) + 
  geom_bar(stat = "identity") +
  geom_text(size = 10, position = position_stack(vjust = .5), color = "red", family = "Palatino") +
  theme_minimal() +
  scale_fill_manual(values = c(EFF1.HQ_MAGs = "#17b2c2", EFF2.HQ_MAGs = "#47ecfd", EFF3.HQ_MAGs = "#29b3fc",
                               EFF1.other_MAGs = "#98e6ee", EFF2.other_MAGs = "#bff8fe", EFF3.other_MAGs = "#b7e0f6",
                               INF1.HQ_MAGs = "#f9e30a", INF2.HQ_MAGs = "#fcf0a0", INF3.HQ_MAGs = "#eac51e",
                               INF1.other_MAGs = "#fef174", INF2.other_MAGs = "#f9f5de", INF3.other_MAGs = "#f0de8e",
                               SLU1.HQ_MAGs = "#e38236", SLU2.HQ_MAGs = "#fec191", SLU3.HQ_MAGs = "#daa187",
                               SLU1.other_MAGs = "#e5aa7c", SLU2.other_MAGs = "#ffdcc0", SLU3.other_MAGs = "#dbbeb1")) +
  ggtitle("Number of MAGs by HiFi MAG Pipeline") +  theme_minimal() +
  scale_y_continuous(expand = c(0,0)) +
  theme(
        text = element_text(family = "Palatino"),
        legend.position = "none",
        axis.title = element_blank(),
        axis.text.y = element_text(size = 30),
        axis.text.x = element_text(size = 24, face = "bold"),
        plot.title = element_text(size = 30))
p

ggsave(filename = "plots/Pipeline_MAGs.png",
       width = 16, height = 13, dpi = 300, units = "in", device='png', scale = 1)
```






